# Generated by Django 3.2.5 on 2021-12-24 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211224_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default='9d35d238-3', max_length=10),
        ),
    ]
