# Generated by Django 3.2.5 on 2021-11-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='79a9fa59', max_length=8),
        ),
    ]
