# Generated by Django 3.2.5 on 2021-12-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211225_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='845efe8f', max_length=8),
        ),
    ]
